# Generated by Django 2.2.14 on 2021-09-12 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('data', models.TextField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('is_liked', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='event_pics')),
            ],
        ),
    ]
